site_name: Xailient Docs
nav:
    - Welcome to Xailient SDK Documentation: index.md
    - Getting Started with Console: console_getting_started.md
    - Datasets: dataset.md
    - Pre-trained AI Models: pre_trained_models.md
    - Train Your Own AI: custom_models.md
    - Evaluate your AI: video_inference.md
    - Build Deployable SDK: buildSdk.md
    - Deploy Your AI: 
        - Native Installation: installation.md
        - Docker Container: container.md
    - Monitor Your AI: monitor.md
    - Subscription: subscribe.md
    - API Documentation: xailient_sdk_api.md 
    - Example Codes and Utilities: sample_code.md
    - FAQs: faqs.md
    - Did not find what you are looking for?: support.md
theme:
    name: material
    custom_dir: overrides
    palette:
      primary: 'deep purple'
      accent: 'deep purple'
    logo: 'img/Xailient_X.png'
    favicon: 'img/favicon.png'
extra_css:
- 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - codehilite